### ISSUE TITLE
quirks mode (don't put before doctype)

### ISSUE THREAD

**Issue by ruggerocastagnola** [jamesgpearce/modernizr-server#4]
Just a caveat for future reference, since i was silly and stumped into it. Hopefully will be useful for someone else.

Never include the library before the <!doctype> declaration, as it's most likely to put the browser in quirks mode and fails markup validation, as it prints out html.

**Comment by serbanghita** [comment]
@ruggerocastagnola that is actually valid for any piece of characters before `<!doctype>`, even spaces.

**Comment by ruggerocastagnola** [comment]
Thanks @serbanghita. I'll try and do some more tests and see if I can isolate what's not working for me, and report it. I couldn't seem to be able to validate my html without removing the library from up there.

**Comment by ruggerocastagnola** [comment]
Thanks @serbanghita (sorry for deleting the comment, I misread your reply).
